#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov  8 13:00:59 2019

@author: Warren.Sink
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#from scipy.misc import imread
from matplotlib.pyplot import imread
from PIL import Image

df = pd.read_csv('schoeller_coord_3n_df.csv')
df_y = pd.read_csv('schoeller_coord_3n_df_y.csv')
df_x = pd.read_csv('schoeller_coord_3n_df_x.csv')

bb = pd.read_csv(filepath_or_buffer = 'schoeller_bb_corners.csv')
bb_y = pd.read_csv(filepath_or_buffer = 'schoeller_bb_corners_y.csv')
bb_x = pd.read_csv(filepath_or_buffer = 'schoeller_bb_corners_x.csv')
#print(df.iloc[0,0])
#print(df.iloc[1,0])
#print(df.iloc[2,0])
#print(df.iloc[0,1])

#print(df.columns[64])

#print(df_y.iloc[0,1])
#print(df_y.iloc[1,0])
#print(df_y.iloc[2,0])
#print(df_y.iloc[0,1])

#print(df.head)
print(df_y.columns)
print(bb_y.head)
print(bb_x.head)
print(bb_y.columns)
print(bb_y.iloc[:,1])
#im = Image.open('Allooh_Jonas.jpg')
#width, height = im.size
#print(width, height)


#np.random.seed(0)
#x = np.random.uniform(0.0,10.0,15)
#y = np.random.uniform(0.0,10.0,15)

def scatter_line_img(IMAGE, landmark_x, landmark_y, bb_x, bb_y, coord):
    img = imread(IMAGE)
    plt.scatter(x = landmark_x.iloc[:,coord], y = landmark_y.iloc[:,coord], c='b', s=15)
    plt.scatter(x = bb_x.iloc[:,coord], y = bb_y.iloc[:,coord], c='r', s=15)
    plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
    plt.plot(bb_x.iloc[:,coord], bb_y.iloc[:,coord])
    plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter-line" + IMAGE + ".pdf")
    plt.show()

scatter_line_img('Allooh_Jonas.jpg', df_x, df_y, bb_x, bb_y, 1)

img = imread('Allooh_Jonas.jpg')
plt.scatter(x = df_x.iloc[:,1], y = df_y.iloc[:,1], c='b', s=15)
plt.scatter(x = bb_x.iloc[:,1], y = bb_y.iloc[:,1], c='r', s=15)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.plot(bb_x.iloc[:,1], bb_y.iloc[:,1])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter-line_Allooh_Jonas.pdf")
plt.show()

img = imread('Allooh_Moses.jpg')
plt.scatter(x=df_x.iloc[:,2], y=df_y.iloc[:,2], c='b', s=25)
plt.scatter(x=bb_x.iloc[:,2], y=bb_y.iloc[:,2], c='r', s=25)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.plot(bb_x.iloc[:,2], bb_y.iloc[:,2])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Allooh_Moses_scatter.pdf")
plt.show()

img = imread('Allooh_Noah.jpg')
plt.scatter(x=df_x.iloc[:,3], y=df_y.iloc[:,3], c='b', s=25)
plt.scatter(x = bb_x.iloc[:,3], y = bb_y.iloc[:,3], c='r', s=25)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.plot(bb_x.iloc[:,3], bb_y.iloc[:,3])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Allooh_Noah_scatter.pdf")
plt.show()

img = imread('Andrews_Doug.jpg')
plt.scatter(x=df_x.iloc[:,4], y=df_y.iloc[:,4], c='b', s=25)
plt.scatter(x=bb_x.iloc[:,4], y=bb_y.iloc[:,4], c='r', s=25)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.plot(bb_x.iloc[:,4], bb_y.iloc[:,4])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Andrews_Doug.pdf")
plt.show()

img = imread('Andrews_Ross.jpg')
plt.scatter(x=df_x.iloc[:,5], y=df_y.iloc[:,5], c='b', s=25)
plt.scatter(x=bb_x.iloc[:,5], y=bb_y.iloc[:,5], c='r', s=25)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.plot(bb_x.iloc[:,5], bb_y.iloc[:,5])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Andrews_Ross.pdf")
plt.show()

img = imread('Ayer_Carly.jpg')
plt.scatter(x=df_x.iloc[:,6], y=df_y.iloc[:,6], c='b', s=25)
plt.scatter(x=bb_x.iloc[:,6], y=bb_y.iloc[:,6], c='r', s=25)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.plot(bb_x.iloc[:,6], bb_y.iloc[:,6])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Ayer_Carly.pdf")
plt.show()

img = imread('Ayer_Lily.jpg')
plt.scatter(x=df_x.iloc[:,7], y=df_y.iloc[:,7], c='b', s=25)
plt.scatter(x=bb_x.iloc[:,7], y=bb_y.iloc[:,7], c='r', s=25)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.plot(bb_x.iloc[:,7], bb_y.iloc[:,7])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Ayer_Lily.pdf")
plt.show()

img = imread('Bowen_David.jpg')
plt.scatter(x=df_x.iloc[:,8], y=df_y.iloc[:,8], c='b', s=25)
plt.scatter(x=bb_x.iloc[:,8], y=bb_y.iloc[:,8], c='r', s=25)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.plot(bb_x.iloc[:,8], bb_y.iloc[:,8])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Bowen_David.pdf")
plt.show()

img = imread('Bowen_Richard.jpg')
plt.scatter(x=df_x.iloc[:,9], y=df_y.iloc[:,9], c='b', s=25)
plt.scatter(x=bb_x.iloc[:,9], y=bb_y.iloc[:,9], c='r', s=25)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.plot(bb_x.iloc[:,9], bb_y.iloc[:,9])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Bowen_Richard.pdf")
plt.show()

img = imread('Bowers_Brenda.jpg')
plt.scatter(x=df_x.iloc[:,10], y=df_y.iloc[:,10], c='b', s=25)
plt.scatter(x=bb_x.iloc[:,10], y=bb_y.iloc[:,10], c='r', s=25)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.plot(bb_x.iloc[:,10], bb_y.iloc[:,10])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Bowers_Brenda.pdf")
plt.show()

img = imread('Braswell_Orlean.jpg')
plt.scatter(x=df_x.iloc[:,11], y=df_y.iloc[:,11], c='b', s=25)
plt.scatter(x=bb_x.iloc[:,11], y=bb_y.iloc[:,11], c='r', s=25)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.plot(bb_x.iloc[:,11], bb_y.iloc[:,11])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Braswell_Orlean.pdf")
plt.show()

img = imread('Bridges_Carolyn.jpg')
plt.scatter(x=df_x.iloc[:,12], y=df_y.iloc[:,12], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Bridges_Carolyn.pdf")
plt.show()

img = imread('Burns_Catherine.jpg')
plt.scatter(x=df_x.iloc[:,13], y=df_y.iloc[:,13], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Burns_Catherine.pdf")
plt.show()

img = imread('Burns_McKenzie.jpg')
plt.scatter(x=df_x.iloc[:,14], y=df_y.iloc[:,14], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Burns_McKenzie.pdf")
plt.show()

img = imread('Catalano_Joe.jpg')
plt.scatter(x=df_x.iloc[:,15], y=df_y.iloc[:,15], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Catalano_Joe.pdf")
plt.show()

img = imread('Catalano_Sal.jpg')
plt.scatter(x=df_x.iloc[:,16], y=df_y.iloc[:,16], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Catalano_Sal.pdf")
plt.show()

img = imread('Cepeda_Eurides.jpg')
plt.scatter(x=df_x.iloc[:,17], y=df_y.iloc[:,17], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Cepeda_Eurides.pdf")
plt.show()

img = imread('Cepeda_Ramon.jpg')
plt.scatter(x=df_x.iloc[:,18], y=df_y.iloc[:,18], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Cepeda_Ramon.pdf")
plt.show()

img = imread('Claucherty_Marion.jpg')
plt.scatter(x=df_x.iloc[:,19], y=df_y.iloc[:,19], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Claucherty_Marion.pdf")
plt.show()

img = imread('Croll-Baehre_Marta.jpg')
plt.scatter(x=df_x.iloc[:,20], y=df_y.iloc[:,20], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Croll.Baehre_Marta.pdf")
plt.show()

img = imread('Croll-Baehre_Emma.jpg')
plt.scatter(x=df_x.iloc[:,21], y=df_y.iloc[:,21], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Croll.Baehre_Emma.pdf")
plt.show()

img = imread('Davis_June.jpg')
plt.scatter(x=df_x.iloc[:,24], y=df_y.iloc[:,24], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Davis_June.pdf")
plt.show()

img = imread('Demonet_David_2.jpg')
plt.scatter(x=df_x.iloc[:,25], y=df_y.iloc[:,25], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Demonet_Larry.pdf")
plt.show()

img = imread('Demonet_Larry_2.jpg')
plt.scatter(x=df_x.iloc[:,26], y=df_y.iloc[:,26], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Demonet_David.pdf")
plt.show()

img = imread('Dwomoh-Piper_Danielle.jpg')
plt.scatter(x=df_x.iloc[:,27], y=df_y.iloc[:,27], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Dwomoh-Piper_Danielle.pdf")
plt.show()

img = imread('Dwomoh-Piper_Chantelle.jpg')
plt.scatter(x=df_x.iloc[:,28], y=df_y.iloc[:,28], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Dwomoh-Piper_Chantelle.pdf")
plt.show()

img = imread('Elder_Marilyn.jpg')
plt.scatter(x=df_x.iloc[:,29], y=df_y.iloc[:,29], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Elder_Marilyn.pdf")
plt.show()

img = imread('Estrada_Antonion.jpg')
plt.scatter(x=df_x.iloc[:,30], y=df_y.iloc[:,30], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Estrada_Antonion.pdf")
plt.show()

img = imread('Estrada_Jesus.jpg')
plt.scatter(x=df_x.iloc[:,31], y=df_y.iloc[:,31], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Estrada_Jesus.pdf")
plt.show()

img = imread('Everingham_Douglas.jpg')
plt.scatter(x=df_x.iloc[:,32], y=df_y.iloc[:,32], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Everingham_Douglas.pdf")
plt.show()

img = imread('Everingham_Steve.jpg')
plt.scatter(x=df_x.iloc[:,33], y=df_y.iloc[:,33], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Everingham_Steve.pdf")
plt.show()

img = imread('Furtick_Jason.jpg')
plt.scatter(x=df_x.iloc[:,34], y=df_y.iloc[:,34], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Furtick_Jason.pdf")
plt.show()

img = imread('Furtick_Kevin.jpg')
plt.scatter(x=df_x.iloc[:,35], y=df_y.iloc[:,35], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Furtick_Kevin.pdf")
plt.show()

img = imread('Furtick_Victor.jpg')
plt.scatter(x=df_x.iloc[:,36], y=df_y.iloc[:,36], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Furtick_Victor.pdf")
plt.show()

img = imread('Furtick_Keith.jpg')
plt.scatter(x=df_x.iloc[:,37], y=df_y.iloc[:,37], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Furtick_Keith.pdf")
plt.show()

img = imread('Garzilli_Denise.jpg')
plt.scatter(x=df_x.iloc[:,38], y=df_y.iloc[:,38], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Garzilli_Denise.pdf")
plt.show()

img = imread('Ginley_Adalynn.jpg')
plt.scatter(x=df_x.iloc[:,39], y=df_y.iloc[:,39], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Ginley_Adalynn.pdf")
plt.show()

img = imread('Ginley_Breanna.jpg')
plt.scatter(x=df_x.iloc[:,40], y=df_y.iloc[:,40], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Ginley_Breanna.pdf")
plt.show()

img = imread('Goldberg_Adam.jpg')
plt.scatter(x=df_x.iloc[:,41], y=df_y.iloc[:,41], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Goldberg_Adam.pdf")
plt.show()

img = imread('Goldberg_Peter.jpg')
plt.scatter(x=df_x.iloc[:,42], y=df_y.iloc[:,42], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Goldberg_Peter.pdf")
plt.show()

img = imread('Haick_Ava.jpg')
plt.scatter(x=df_x.iloc[:,43], y=df_y.iloc[:,43], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Haick_Ava.pdf")
plt.show()

img = imread('Haick_Isabel.jpg')
plt.scatter(x=df_x.iloc[:,44], y=df_y.iloc[:,44], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Haick_Isabel.pdf")
plt.show()

img = imread('Hudson_Irene.jpg')
plt.scatter(x=df_x.iloc[:,45], y=df_y.iloc[:,45], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Hudson_Irene.pdf")
plt.show()

img = imread('Humphery_Emma.jpg')
plt.scatter(x=df_x.iloc[:,46], y=df_y.iloc[:,46], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Humphery_Emma.pdf")
plt.show()

img = imread('Humphery_Megan.jpg')
plt.scatter(x=df_x.iloc[:,47], y=df_y.iloc[:,47], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Humphery_Megan.pdf")
plt.show()

img = imread('Humphery_Sarah.jpg')
plt.scatter(x=df_x.iloc[:,48], y=df_y.iloc[:,48], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Humphery_Sarah.pdf")
plt.show()

img = imread('Jackson_Sidney.jpg')
plt.scatter(x=df_x.iloc[:,49], y=df_y.iloc[:,49], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Jackson_Sidney.pdf")
plt.show()

img = imread('Jacques_Mary.jpg')
plt.scatter(x=df_x.iloc[:,50], y=df_y.iloc[:,50], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Jacques_Mary.pdf")
plt.show()

img = imread('Jensen_Dane.jpg')
plt.scatter(x=df_x.iloc[:,51], y=df_y.iloc[:,51], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Jensen_Dane.pdf")
plt.show()

img = imread('Jensen_Jordan.jpg')
plt.scatter(x=df_x.iloc[:,52], y=df_y.iloc[:,52], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Jensen_Jordan.pdf")
plt.show()

img = imread('Kerner_Sharon.jpg')
plt.scatter(x=df_x.iloc[:,55], y=df_y.iloc[:,55], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Kerner_Sharon.pdf")
plt.show()

img = imread('Key_Aidan.jpg')
plt.scatter(x=df_x.iloc[:,56], y=df_y.iloc[:,56], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Key_Aidan.pdf")
plt.show()

img = imread('Kobylski_Cecelia.jpg')
plt.scatter(x=df_x.iloc[:,57], y=df_y.iloc[:,57], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Kobylski_Cecelia.pdf")
plt.show()

img = imread('Kobylski_Elizabeth.jpg')
plt.scatter(x=df_x.iloc[:,58], y=df_y.iloc[:,58], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Kobylski_Elizabeth.pdf")
plt.show()

img = imread('Lipfird_Garry.jpg')
plt.scatter(x=df_x.iloc[:,59], y=df_y.iloc[:,59], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Lipfird_Garry.pdf")
plt.show()

img = imread('Lipfird_Larry.jpg')
plt.scatter(x=df_x.iloc[:,60], y=df_y.iloc[:,60], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Lipfird_Larry.pdf")
plt.show()

img = imread('Maassen_Jamie.jpg')
plt.scatter(x=df_x.iloc[:,63], y=df_y.iloc[:,63], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Maassen_Jamie.pdf")
plt.show()

img = imread('Martin_Kate.jpg')
plt.scatter(x=df_x.iloc[:,64], y=df_y.iloc[:,64], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Martin_Kate.pdf")
plt.show()

img = imread('Martin_emily.jpg')
plt.scatter(x=df_x.iloc[:,65], y=df_y.iloc[:,65], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Martin_Emily.pdf")
plt.show()

img = imread('McClure_Bryan.jpg')
plt.scatter(x=df_x.iloc[:,66], y=df_y.iloc[:,66], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_McClure_Bryan.pdf")
plt.show()

img = imread('McClure_Bryce.jpg')
plt.scatter(x=df_x.iloc[:,67], y=df_y.iloc[:,67], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_McClure_Bryce.pdf")
plt.show()

img = imread('McLeod_Keisher.jpg')
plt.scatter(x=df_x.iloc[:,68], y=df_y.iloc[:,68], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_McLeod_Keisher.pdf")
plt.show()

img = imread('McLeod_Teisher.jpg')
plt.scatter(x=df_x.iloc[:,69], y=df_y.iloc[:,69], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_McLeod_Teisher.pdf")
plt.show()

img = imread('Mielke_Alyssa.jpg')
plt.scatter(x=df_x.iloc[:,70], y=df_y.iloc[:,70], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Mielke_Alyssa.pdf")
plt.show()

img = imread('Mielke_Emily.jpg')
plt.scatter(x=df_x.iloc[:,71], y=df_y.iloc[:,71], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Mielke_Emily.pdf")
plt.show()

img = imread('Mitchell_Fred.jpg')
plt.scatter(x=df_x.iloc[:,72], y=df_y.iloc[:,72], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Mitchell_Fred.pdf")
plt.show()

img = imread('Mitchell_Ned.jpg')
plt.scatter(x=df_x.iloc[:,73], y=df_y.iloc[:,73], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Mitchell_Ned.pdf")
plt.show()

img = imread('Moyer_Jean.jpg')
plt.scatter(x=df_x.iloc[:,74], y=df_y.iloc[:,74], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Moyer_Jean.pdf")
plt.show()

img = imread('Mueller_Kirk_2.jpg')
plt.scatter(x=df_x.iloc[:,75], y=df_y.iloc[:,75], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Mueller_Kirk.pdf")
plt.show()

img = imread('Mueller_Nate_2.jpg')
plt.scatter(x=df_x.iloc[:,76], y=df_y.iloc[:,76], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Mueller_Nate.pdf")
plt.show()

img = imread('Nagel_Jeff.jpg')
plt.scatter(x=df_x.iloc[:,77], y=df_y.iloc[:,77], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Nagel_Jeff.pdf")
plt.show()

img = imread('Nagel_Steve.jpg')
plt.scatter(x=df_x.iloc[:,78], y=df_y.iloc[:,78], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Nagel_Steve.pdf")
plt.show()

img = imread('Nelson_Audri.jpg')
plt.scatter(x=df_x.iloc[:,79], y=df_y.iloc[:,79], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Nelson_Audri.pdf")
plt.show()

img = imread('Nelson_Erin.jpg')
plt.scatter(x=df_x.iloc[:,80], y=df_y.iloc[:,80], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Nelson_Erin.pdf")
plt.show()

img = imread('Nick_Spencer.jpg')
plt.scatter(x=df_x.iloc[:,81], y=df_y.iloc[:,81], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Nick_Spencer.pdf")
plt.show()

img = imread('Nick_Skyler.jpg')
plt.scatter(x=df_x.iloc[:,82], y=df_y.iloc[:,82], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Nick_Skyler.pdf")
plt.show()

img = imread('Oliver_David.jpg')
plt.scatter(x=df_x.iloc[:,83], y=df_y.iloc[:,83], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Oliver_David.pdf")
plt.show()

img = imread('Oliver_Walter.jpg')
plt.scatter(x=df_x.iloc[:,84], y=df_y.iloc[:,84], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Oliver_Walter.pdf")
plt.show()

img = imread('Parks_Katie.jpg')
plt.scatter(x=df_x.iloc[:,85], y=df_y.iloc[:,85], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Parks_Katie.pdf")
plt.show()

img = imread('Parks_Sarah.jpg')
plt.scatter(x=df_x.iloc[:,86], y=df_y.iloc[:,86], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Parks_Sarah.pdf")
plt.show()

img = imread('Prijatel.jpg')
plt.scatter(x=df_x.iloc[:,87], y=df_y.iloc[:,87], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Prijatel.pdf")
plt.show()

img = imread('Qualkinbush_Jodie.jpg')
plt.scatter(x=df_x.iloc[:,88], y=df_y.iloc[:,88], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Qualkinbush_Jodie.pdf")
plt.show()

img = imread('Rabi_Kate.jpg')
plt.scatter(x=df_x.iloc[:,89], y=df_y.iloc[:,89], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Rabi_Kate.pdf")
plt.show()

img = imread('Ramsdell_Cole.jpg')
plt.scatter(x=df_x.iloc[:,90], y=df_y.iloc[:,90], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Ramsdell_Cole.pdf")
plt.show()

img = imread('Ramsdell_Seth.jpg')
plt.scatter(x=df_x.iloc[:,91], y=df_y.iloc[:,91], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Ramsdell_Seth.pdf")
plt.show()

img = imread('Ream_Alyssa.jpg')
plt.scatter(x=df_x.iloc[:,92], y=df_y.iloc[:,92], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Ream_Alyssa.pdf")
plt.show()

img = imread('Ream_Rachel.jpg')
plt.scatter(x=df_x.iloc[:,93], y=df_y.iloc[:,93], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Ream_Rachel.pdf")
plt.show()

img = imread('Rowan_Hannah.jpg')
plt.scatter(x=df_x.iloc[:,94], y=df_y.iloc[:,94], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Rowan_Hannah.pdf")
plt.show()

img = imread('Rowan_Kaci.jpg')
plt.scatter(x=df_x.iloc[:,95], y=df_y.iloc[:,95], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Rowan_Kaci.pdf")
plt.show()

img = imread('Scott-Wolf_Adriana.jpg')
plt.scatter(x=df_x.iloc[:,96], y=df_y.iloc[:,96], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Scott-Wolf_Adriana.pdf")
plt.show()

img = imread('Serra_Ivory.jpg')
plt.scatter(x=df_x.iloc[:,97], y=df_y.iloc[:,97], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Serra_Ivory.pdf")
plt.show()

img = imread('Serra_Shelter.jpg')
plt.scatter(x=df_x.iloc[:,98], y=df_y.iloc[:,98], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Serra_Shelter.pdf")
plt.show()

img = imread('Smith_Connor.jpg')
plt.scatter(x=df_x.iloc[:,99], y=df_y.iloc[:,99], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Smith_Connor.pdf")
plt.show()

img = imread('Smith_Kyle.jpg')
plt.scatter(x=df_x.iloc[:,100], y=df_y.iloc[:,100], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Smith_Kyle.pdf")
plt.show()

img = imread('Starr_Ellen.jpg')
plt.scatter(x=df_x.iloc[:,101], y=df_y.iloc[:,101], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Starr_Ellen.pdf")
plt.show()

img = imread('Steeves_Carrie.jpg')
plt.scatter(x=df_x.iloc[:,102], y=df_y.iloc[:,102], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Steeves_Carrie.pdf")
plt.show()

img = imread('Steeves_Patty.jpg')
plt.scatter(x=df_x.iloc[:,103], y=df_y.iloc[:,103], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Steeves_Patty.pdf")
plt.show()

img = imread('Stewart_Martha.jpg')
plt.scatter(x=df_x.iloc[:,104], y=df_y.iloc[:,104], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Stewart_Martha.pdf")
plt.show()

img = imread('Stillwell_Diane.jpg')
plt.scatter(x=df_x.iloc[:,105], y=df_y.iloc[:,105], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Stillwell_Diane.pdf")
plt.show()

img = imread('Thornhill_Jennie.jpg')
plt.scatter(x=df_x.iloc[:,106], y=df_y.iloc[:,106], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Thornhill_Jennie.pdf")
plt.show()

img = imread('Timotiwu_Jason.jpg')
plt.scatter(x=df_x.iloc[:,107], y=df_y.iloc[:,107], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Timotiwu_Jason.pdf")
plt.show()

img = imread('Timotiwu_Jordan.jpg')
plt.scatter(x=df_x.iloc[:,108], y=df_y.iloc[:,108], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Timotiwu_Jordan.pdf")
plt.show()

img = imread('Tynski_Daniel.jpg')
plt.scatter(x=df_x.iloc[:,109], y=df_y.iloc[:,109], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Tynski_Daniel.pdf")
plt.show()

img = imread('Tynski_Kristen.jpg')
plt.scatter(x=df_x.iloc[:,110], y=df_y.iloc[:,110], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Tynski_Kristen.pdf")
plt.show()

img = imread('Ullman_Helen.jpg')
plt.scatter(x=df_x.iloc[:,111], y=df_y.iloc[:,111], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Bridges_Carolyn.pdf")
plt.show()

img = imread('Underwood_Helen.jpg')
plt.scatter(x=df_x.iloc[:,112], y=df_y.iloc[:,112], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Bridges_Carolyn.pdf")
plt.show()

img = imread('Whited_Jackie.jpg')
plt.scatter(x=df_x.iloc[:,113], y=df_y.iloc[:,113], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Bridges_Carolyn.pdf")
plt.show()

img = imread('Whited_Jessica.jpg')
plt.scatter(x=df_x.iloc[:,114], y=df_y.iloc[:,114], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Bridges_Carolyn.pdf")
plt.show()

img = imread('Widerka_Amanda.jpg')
plt.scatter(x=df_x.iloc[:,115], y=df_y.iloc[:,115], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Bridges_Carolyn.pdf")
plt.show()

img = imread('Widerka_Beth.jpg')
plt.scatter(x=df_x.iloc[:,116], y=df_y.iloc[:,116], c='b', s=25)
#plt.scatter(5, 6)
#plt.scatter(x=[4, 4], y=[3, 3], c='r', s=40)
plt.imshow(img, zorder=0, extent=[0, 1275, 0, 2100])
plt.savefig(fname = "/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/scatter_Bridges_Carolyn.pdf")
plt.show()












