#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov  8 13:00:59 2019

@author: Warren.Sink
"""
import os
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.pyplot import imread
from PIL import Image

os.chdir("/Users/Warren.Sink/github/facial-polyphenism/CSVs")

df = pd.read_csv('schoeller_extract_nonnosenorm.csv')
df_y = pd.read_csv('schoeller_extract_nonnosenorm_y.csv')
df_x = pd.read_csv('schoeller_extract_nonnosenorm_x.csv')


os.chdir("/Users/Warren.Sink/Desktop/OneDrive-Van-Andel-Institute/Schoeller_IMGs/extracted-faces")
target_dir = "/Users/Warren.Sink/github/facial-polyphenism/scatterplot-images/schoeller-extract/"

im = Image.open('Allooh_Jonas.jpg')
width, height = im.size
print(width, height)

def scatterp_img(IMAGE, landmark_x, landmark_y, order):
    img = imread(IMAGE)
    im = Image.open(IMAGE)
    width, height = im.size
    plt.scatter(x = landmark_x.iloc[:,order], y = landmark_y.iloc[:,order], c='b', s=15)
    plt.imshow(img, zorder=0, extent=[0, width, 0, height])
    plt.savefig(fname = target_dir + IMAGE[:-4] + ".pdf")
    plt.show()

scatterp_img('Allooh_Jonas.jpg', df_x, df_y, 1)
scatterp_img('Allooh_Moses.jpg', df_x, df_y, 2)
scatterp_img('Allooh_Noah.jpg', df_x, df_y, 3)
scatterp_img('Andrews_Doug.jpg', df_x, df_y, 4)
scatterp_img('Andrews_Ross.jpg', df_x, df_y,5)
scatterp_img('Ayer_Carly.jpg', df_x, df_y, 6)
scatterp_img('Ayer_Lily.jpg', df_x, df_y, 7)
scatterp_img('Bowen_David.jpg', df_x, df_y, 8)
scatterp_img('Bowen_Richard.jpg', df_x, df_y, 9)
scatterp_img('Bowers_Brenda.jpg', df_x, df_y, 10)
scatterp_img('Braswell_Orlean.jpg', df_x, df_y, 11)
scatterp_img('Bridges_Carolyn.jpg', df_x, df_y, 12)
scatterp_img('Burns_Catherine.jpg', df_x, df_y, 13)
scatterp_img('Burns_McKenzie.jpg', df_x, df_y, 14)
scatterp_img('Catalano_Joe.jpg', df_x, df_y, 15)
scatterp_img('Catalano_Sal.jpg', df_x, df_y, 16)
scatterp_img('Cepeda_Eurides.jpg', df_x, df_y, 17)
scatterp_img('Cepeda_Ramon.jpg', df_x, df_y, 18)
scatterp_img('Claucherty_Marion.jpg', df_x, df_y, 19)
scatterp_img('Croll-Baehre_Emma.jpg', df_x, df_y, 20)
scatterp_img('Croll-Baehre_Marta.jpg', df_x, df_y, 21)
scatterp_img('Darren_1.jpg', df_x, df_y, 22)
scatterp_img('Darren_2.jpg', df_x, df_y, 23)
scatterp_img('Davis_June.jpg', df_x, df_y, 24)
scatterp_img('Demonet_David.jpg', df_x, df_y, 25)
scatterp_img('Demonet_Larry.jpg', df_x, df_y, 26)
scatterp_img('Dwomoh-Piper_Chantelle.jpg', df_x, df_y, 27)
scatterp_img('Dwomoh-Piper_Danielle.jpg', df_x, df_y, 28)
scatterp_img('Elder_Marilyn.jpg', df_x, df_y, 29)
scatterp_img('Estrada_Antonion.jpg', df_x, df_y, 30)
scatterp_img('Estrada_Jesus.jpg', df_x, df_y, 31)
scatterp_img('Everingham_Douglas.jpg', df_x, df_y, 32)
scatterp_img('Everingham_Steve.jpg', df_x, df_y, 33)
scatterp_img('Furtick_Jason.jpg', df_x, df_y, 34)
scatterp_img('Furtick_Keith.jpg', df_x, df_y, 35)
scatterp_img('Furtick_Kevin.jpg', df_x, df_y, 36)
scatterp_img('Furtick_Victor.jpg', df_x, df_y, 37)
scatterp_img('Garzilli_Denise.jpg', df_x, df_y, 38)
scatterp_img('Ginley_Adalynn.jpg', df_x, df_y, 39)
scatterp_img('Ginley_Breanna.jpg', df_x, df_y, 40)
scatterp_img('Goldberg_Adam.jpg', df_x, df_y, 41)
scatterp_img('Goldberg_Peter.jpg', df_x, df_y, 42)
scatterp_img('Haick_Ava.jpg', df_x, df_y, 43)
scatterp_img('Haick_Isabel.jpg', df_x, df_y, 44)
scatterp_img('Hudson_Irene.jpg', df_x, df_y, 45)
scatterp_img('Humphery_Emma.jpg', df_x, df_y, 46)
scatterp_img('Humphery_Megan.jpg', df_x, df_y, 47)
scatterp_img('Humphery_Sarah.jpg', df_x, df_y, 48)
scatterp_img('Jackson_Sidney.jpg', df_x, df_y, 49)
scatterp_img('Jacques_Mary.jpg', df_x, df_y, 50)
scatterp_img('Jensen_Dane.jpg', df_x, df_y, 51)
scatterp_img('Jensen_Jordan.jpg', df_x, df_y, 52)
scatterp_img('Karen_1.jpg', df_x, df_y, 53)
scatterp_img('Karen_2.jpg', df_x, df_y, 54)
scatterp_img('Kerner_Sharon.jpg', df_x, df_y, 55)
scatterp_img('Key_Aidan.jpg', df_x, df_y, 56)
scatterp_img('Kobylski_Cecelia.jpg', df_x, df_y, 57)
scatterp_img('Kobylski_Elizabeth.jpg', df_x, df_y, 58)
scatterp_img('Lipfird_Garry.jpg', df_x, df_y, 59)
scatterp_img('Lipfird_Larry.jpg', df_x, df_y, 60)
scatterp_img('Lois_1.jpg', df_x, df_y, 61)
scatterp_img('Lois_2.jpg', df_x, df_y, 62)
scatterp_img('Maassen_Jamie.jpg', df_x, df_y, 63)
scatterp_img('Martin_Emily.jpg', df_x, df_y, 64)
scatterp_img('Martin_Kate.jpg', df_x, df_y, 65)
scatterp_img('McClure_Bryan.jpg', df_x, df_y, 66)
scatterp_img('McClure_Bryce.jpg', df_x, df_y, 67)
scatterp_img('McLeod_Keisher.jpg', df_x, df_y, 68)
scatterp_img('McLeod_Teisher.jpg', df_x, df_y, 69)
scatterp_img('Mielke_Alyssa.jpg', df_x, df_y, 70)
scatterp_img('Mielke_Emily.jpg', df_x, df_y, 71)
scatterp_img('Mitchell_Fred.jpg', df_x, df_y, 72)
scatterp_img('Mitchell_Ned.jpg', df_x, df_y, 73)
scatterp_img('Moyer_Jean.jpg', df_x, df_y, 74)
scatterp_img('Mueller_Kirk.jpg', df_x, df_y, 75)
scatterp_img('Mueller_Nate.jpg', df_x, df_y, 76)
scatterp_img('Nagel_Jeff.jpg', df_x, df_y, 77)
scatterp_img('Nagel_Steve.jpg', df_x, df_y, 78)
scatterp_img('Nelson_Audri.jpg', df_x, df_y, 79)
scatterp_img('Nelson_Erin.jpg', df_x, df_y, 80)
scatterp_img('Nick_Skyler.jpg', df_x, df_y, 81)
scatterp_img('Nick_Spencer.jpg', df_x, df_y, 82)
scatterp_img('Oliver_David.jpg', df_x, df_y, 83)
scatterp_img('Oliver_Walter.jpg', df_x, df_y, 84)
scatterp_img('Parks_Katie.jpg', df_x, df_y, 85)
scatterp_img('Parks_Sarah.jpg', df_x, df_y, 86)
scatterp_img('Prijatel.jpg', df_x, df_y, 87)
scatterp_img('Qualkinbush_Jodie.jpg', df_x, df_y, 88)
scatterp_img('Rabi_Kate.jpg', df_x, df_y, 89)
scatterp_img('Ramsdell_Cole.jpg', df_x, df_y, 90)
scatterp_img('Ramsdell_Seth.jpg', df_x, df_y, 91)
scatterp_img('Ream_Alyssa.jpg', df_x, df_y, 92)
scatterp_img('Ream_Rachel.jpg', df_x, df_y, 93)
scatterp_img('Rowan_Hannah.jpg', df_x, df_y, 94)
scatterp_img('Rowan_Kaci.jpg', df_x, df_y, 95)
scatterp_img('Scott-Wolf_Adriana.jpg', df_x, df_y, 96)
scatterp_img('Serra_Ivory.jpg', df_x, df_y, 97)
scatterp_img('Serra_Shelter.jpg', df_x, df_y, 98)
scatterp_img('Smith_Connor.jpg', df_x, df_y, 99)
scatterp_img('Smith_Kyle.jpg', df_x, df_y, 100)
scatterp_img('Starr_Ellen.jpg', df_x, df_y, 101)
scatterp_img('Steeves_Carrie.jpg', df_x, df_y, 102)
scatterp_img('Steeves_Patty.jpg', df_x, df_y, 103)
scatterp_img('Stewart_Martha.jpg', df_x, df_y, 104)
scatterp_img('Stillwell_Diane.jpg', df_x, df_y, 105)
scatterp_img('Thornhill_Jennie.jpg', df_x, df_y, 106)
scatterp_img('Timotiwu_Jason.jpg', df_x, df_y, 107)
scatterp_img('Timotiwu_Jordan.jpg', df_x, df_y, 108)
scatterp_img('Tynski_Daniel.jpg', df_x, df_y, 109)
scatterp_img('Tynski_Kristen.jpg', df_x, df_y, 110)
scatterp_img('Ullman_Helen.jpg', df_x, df_y, 111)
scatterp_img('Underwood_Helen.jpg', df_x, df_y, 112)
scatterp_img('Whited_Jackie.jpg', df_x, df_y, 113)
scatterp_img('Whited_Jessica.jpg', df_x, df_y, 114)
scatterp_img('Widerka_Amanda.jpg', df_x, df_y, 115)
scatterp_img('Widerka_Beth.jpg', df_x, df_y, 116)



